# Generated by Django 4.1.7 on 2023-03-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
    ]
